DB_TYPE=postgresdb
DB_POSTGRESDB_HOST=postgres
DB_POSTGRESDB_PORT=5432
DB_POSTGRESDB_DATABASE=n8n
DB_POSTGRESDB_USER=n8n
DB_POSTGRESDB_PASSWORD=${N8N_DB_PASS}

N8N_HOST=${N8N_DOMAIN}
N8N_PORT=5678
N8N_PROTOCOL=${N8N_PROTOCOL}
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
WEBHOOK_URL=${N8N_PROTOCOL}://${N8N_DOMAIN}/
N8N_EDITOR_BASE_URL=${N8N_PROTOCOL}://${N8N_DOMAIN}/

# Sicurezza consigliata (abilita se vuoi proteggere GUI n8n)
# N8N_BASIC_AUTH_ACTIVE=true
# N8N_BASIC_AUTH_USER=admin
# N8N_BASIC_AUTH_PASSWORD=CHANGEME
